services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-miguafi}
      POSTGRES_USER: ${POSTGRES_USER:-miguafi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-miguafi}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # UI

  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-miguafi}:${POSTGRES_PASSWORD:-miguafi}@db:5432/${POSTGRES_DB:-miguafi}
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SECRET_KEY: ${SECRET_KEY:-dev-secret}
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      STORAGE_BACKEND: ${STORAGE_BACKEND:-s3}
      STORAGE_LOCAL_DIR: /app/uploads
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      S3_REGION: us-east-1
      S3_BUCKET: ${S3_BUCKET:-miguafi}
      S3_PUBLIC_BASE_URL: http://localhost:9000/${S3_BUCKET:-miguafi}
    depends_on:
      - db
      - mailhog
      - minio
      - minio-setup
    ports:
      - "8000:8000"
    volumes:
      - api_uploads:/app/uploads

  web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "${WEB_PORT:-5173}:80"
    depends_on:
      - api

  web-dev:
    image: node:20-alpine
    working_dir: /workspace/web
    command: sh -lc "npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --strictPort"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "${WEB_DEV_PORT:-5174}:5173"
    volumes:
      - ../web:/workspace/web
    depends_on:
      - api
      - minio

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      - minio
    entrypoint: |
      /bin/sh -c "
      mc alias set local http://minio:9000 ${S3_ACCESS_KEY:-minioadmin} ${S3_SECRET_KEY:-minioadmin};
      mc mb -p local/${S3_BUCKET:-miguafi} || true;
      mc anonymous set download local/${S3_BUCKET:-miguafi} || true;
      exit 0;
      "

volumes:
  db_data:
  minio_data:
  api_uploads:
