"""
Revision ID: a7a71e539771
Revises: 
Create Date: 2025-10-16 03:59:26.749178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a71e539771'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dogs',
    sa.Column('user_id', sa.String(length=8), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'dog_id')
    )
    op.create_index(op.f('ix_user_dogs_dog_id'), 'user_dogs', ['dog_id'], unique=False)
    op.create_index(op.f('ix_user_dogs_user_id'), 'user_dogs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dogs_user_id'), table_name='user_dogs')
    op.drop_index(op.f('ix_user_dogs_dog_id'), table_name='user_dogs')
    op.drop_table('user_dogs')
    op.drop_table('dogs')
    # ### end Alembic commands ###
