"""
Revision ID: c5ff936cc90c
Revises: a7a71e539771
Create Date: 2025-10-16 04:02:12.307788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ff936cc90c'
down_revision = 'a7a71e539771'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for SQLite ###
    with op.batch_alter_table('user_dogs') as batch_op:
        batch_op.create_unique_constraint('uq_user_dog', ['user_id', 'dog_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for SQLite ###
    with op.batch_alter_table('user_dogs') as batch_op:
        batch_op.drop_constraint('uq_user_dog', type_='unique')
    # ### end Alembic commands ###
